/*
 * Decompiled with CFR 0_119.
 */
package com.a.b.a.a.c;

public enum y {
    RANGE_BONUS_PASSIVE_1,
    RANGE_BONUS_AURA_1,
    RANGE_BONUS_PASSIVE_2,
    RANGE_BONUS_AURA_2,
    ADVANCED_MAGIC_MISSILE,
    MAGICAL_DAMAGE_BONUS_PASSIVE_1,
    MAGICAL_DAMAGE_BONUS_AURA_1,
    MAGICAL_DAMAGE_BONUS_PASSIVE_2,
    MAGICAL_DAMAGE_BONUS_AURA_2,
    FROST_BOLT,
    STAFF_DAMAGE_BONUS_PASSIVE_1,
    STAFF_DAMAGE_BONUS_AURA_1,
    STAFF_DAMAGE_BONUS_PASSIVE_2,
    STAFF_DAMAGE_BONUS_AURA_2,
    FIREBALL,
    MOVEMENT_BONUS_FACTOR_PASSIVE_1,
    MOVEMENT_BONUS_FACTOR_AURA_1,
    MOVEMENT_BONUS_FACTOR_PASSIVE_2,
    MOVEMENT_BONUS_FACTOR_AURA_2,
    HASTE,
    MAGICAL_DAMAGE_ABSORPTION_PASSIVE_1,
    MAGICAL_DAMAGE_ABSORPTION_AURA_1,
    MAGICAL_DAMAGE_ABSORPTION_PASSIVE_2,
    MAGICAL_DAMAGE_ABSORPTION_AURA_2,
    SHIELD;
    

    private y() {
    }
}

